### GET POSTS
GET http://localhost:8000/api/posts

### GET POST
GET http://localhost:8000/api/posts/1

### CREATE POST
POST http://localhost:8000/api/posts
Content-Type: application/json

{
  "title": "Post Title 101",
  "content": "Content 101"
}

### UPDATE POST
PUT http://localhost:8000/api/posts/1
Content-Type: application/json

{
  "title": "Post Title Updated 1",
  "content": "Content Updated 1"
}

### DELETE POST
DELETE http://localhost:8000/api/posts/99

